config/routes.rb
Rails.application.routes.draw do
  get 'user_groups/index'

  get 'user_groups/new'

  get 'user_groups/create'

  get 'user_groups/edit'

  get 'user_groups/update'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'home#index'

  resources :users

  get 'sessions/new'
  get 'sessions/destroy'

  get 'signup' => 'users#new'
  get 'find'   => 'users#index'
  get 'profile' => 'users#show'
  get 'home' => 'users#home'
  get 'profile/edit' => 'users#edit'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :relationships
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :user_groups

  resources :albums
  resources :pictures, only: [:new, :create, :edit, :update, :destroy]

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	belongs_to :user 

	validates :name, presence: true, length: { minimum: 2 }
	validates_uniqueness_of :name, scope: :user_id 

	def self.insert_new(user, name)
		group = UserGroup.new(user_id: user.id, name: name)
		group.save 
	end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :logged_in_user

  # Lists all the members of the 
  # group. If no id param is given,
  # assume to look at current_user's
  # group. URL should look like:
  # root_url/usergroups/friends
  # to see the current_user's friends
  # and 
  # root_url/usergroups/id/friends
  # to see the user with id "id"'s friends
  def index
    id = -1 
    if params[:id] 
        id = params[:id]
    else 
        id = current_user.id 
    end 

    @user  = User.find(id)
    @group = UserGroup.find_by(user_id: id, name: params[:group])

    if !@group.nil?
        @group_members = get_members(@user, @group)
    end 

  end

  def show
    id = -1 
    if params[:id] 
        id = params[:id]
    else 
        id = current_user.id 
    end 

    @user  = User.find(id)
    @group = UserGroup.find_by(user_id: id, name: params[:group])
    @group_members = @user.relationships.where(user_id: @user.id, 
                                               group_id: @group.id)
    other_relationships = [] 
    other_relationships << @user.inverse_relationships

    # Append relationships for the same group name
    # where the selected user's id is the
    # foreign key.
    # NOTE: 
    # The first loop loops through ActiveRecord 
    # Association objects
    for assoc in other_relationships
        for r in assoc 
            if r.usergroup.name == @group.name 
                (@group_members ||= []) << r 
            end 
        end
    end 
  end 

  def new
    @group = UserGroup.new
  end

  def create
    @group = UserGroup.new(group_params)
    
    if @group.user_id != current_user.id 
        flash[:danger] = "There was an error creating your group."
        render "new"
    end 

    if @group.save 
        flash[:success] = "Successfully created the group: " + @group.name + "!"
        redirect_to home_path 
    else 
        render "new"
    end 

  end

  def edit
    
    if params[:id].to_i != current_user.id
        redirect_to home_path 
    end 

    @group = UserGroup.find_by(user_id: params[:id],
                               name: params[:group])

    if @group.nil?
        redirect_to home_path 
    end 

    @group_members = get_members(current_user, @group)

  end

  def update
  end

  def destroy 
  end 

  private 

    def get_members(user, group)
        group_members = user.relationships.where(user_id: user.id, 
                                                   group_id: group.id)
        other_relationships = [] 
        other_relationships << user.inverse_relationships

        # Append relationships for the same group name
        # where the selected user's id is the
        # foreign key.
        # NOTE: 
        # The first loop loops through ActiveRecord 
        # Association objects
        for assoc in other_relationships
            for r in assoc 
                if r.usergroup.name == group.name 
                    (group_members ||= []) << r 
                end 
            end
        end

        return group_members 
    end 

    def group_params 
        params.require(:user_group).permit(:name, :user_id)
    end 

end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/edit.html.erb
<% provide(:title, "FotoShare - Edit #{@group.name}") %>
<% provide(:maintitle, "Edit #{@group.name}") %>

<h2>Members</h2>

app/views/user_groups/index.html.erb
<% provide(:title, "FotoShare - #{@user.username}'s Groups") %>

<% if @user.id != current_user.id %>
	<% provide(:maintitle, "#{@user.username}'s Groups") %>
<% else %>
	<% provide(:maintitle, "Your Groups") %>
<% end %>

<ul>
	<% for g in @user.user_groups %>
		<li>
			<%= link_to g.name, user_group_path(:id => @user.id, :group => g.name) %>
			<span>
				<% if @user.id == current_user.id %>
					<%= link_to "(Edit)", edit_user_group_path(:id => @user.id, :group => g.name) %>
				<% end %>
			</span>
		</li>	
	<% end %>
</ul>

app/views/user_groups/new.html.erb
<% provide(:title, "FotoShare - New Group") %>
<% provide(:maintitle, "Create a new Group") %>

<%= form_for @group, url: user_groups_path(@group) do |f| %>
  <%= render 'shared/group_error_messages' %>

  <div class="form-group">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.label :name %> <br />
    <%= f.text_field :name, :class => "form-control",
      :placeholder => "Enter group name..." %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Group", :class => "btn btn-primary" %> 
  </div>
<% end %>

app/views/user_groups/show.html.erb
<% provide(:title, "FotoShare - #{@group.name}") %>
<% provide(:maintitle, "#{@group.name}") %>

<h2>Members</h2>

<% if @group_members %>
	<ul>
		<% for relationship in @group_members %>
			<li>
				<% if relationship.user_id == current_user.id %>
					<%= link_to relationship.relationship.username, user_path(relationship.relationship) %>
				<% else %>
				<%= link_to relationship.user.username, user_path(relationship.user) %>
				<% end %>
			</li>
		<% end %>
	</ul>
<% end %>