config/routes.rb
Rails.application.routes.draw do
  get 'user_groups/index'

  get 'user_groups/new'

  get 'user_groups/create'

  get 'user_groups/edit'

  get 'user_groups/update'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'home#index'

  resources :users

  get 'sessions/new'
  get 'sessions/destroy'

  get 'signup' => 'users#new'
  get 'find'   => 'users#index'
  get 'profile' => 'users#show'
  get 'home' => 'users#home'
  get 'profile/edit' => 'users#edit'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :relationships
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :user_groups

  resources :albums
  resources :pictures, only: [:new, :create, :edit, :update, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base

  # =========================================================================
  # Pseudo Attributes 
  # =========================================================================	
  attr_accessor :remember_token 
  attr_accessor :password_confirmation
  attr_accessor :activation_token 
  attr_accessor :reset_token 
  attr_accessor :name 
  # =========================================================================

  # =========================================================================
  # Associations 
  # =========================================================================
  has_many :albums, dependent: :destroy
  has_many :user_groups 
  has_many :relationships, -> { where(relationships: { status: :accept }) }
  has_many :inverse_relationships, -> { where(relationships: { status: :accept }) },
  :class_name => "Relationship", :foreign_key => :other_user_id 

  has_many :pending_relationships, -> { where(relationships: { status: :pending }) } ,
  :class_name => "Relationship"
  has_many :inverse_pending_relationships, -> { where(relationships: { status: :pending }) } ,
  :class_name => "Relationship", :foreign_key => :other_user_id
  # has_many :pending_relationships, -> { where(relationships: { status: :pending });
  # 		 order('UserGroup.name DESC') },
  #          :through => :relationships, :source => :relationship
  # =========================================================================

  before_save :downcase_email 
  before_create :create_activation_digest 

  # =========================================================================
  # Validation
  # =========================================================================	
  validates :password, presence: true,
  length: { minimum: 8 }
  validates_confirmation_of :password 
  validates :firstname, presence: true 
  validates :lastname,  presence: true 
  validates :username, presence: true,
  length: { minimum: 5, maximum: 30 },
  uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
  uniqueness: { case_sensitive: false }, 
  presence: true

  has_secure_password
  # =========================================================================

  # =========================================================================
  # Gettters and setters
  # =========================================================================
  def name
    @name = self.firstname + " " + self.lastname 
  end 
  # =========================================================================

  # =========================================================================
  # Helper methods 
  # =========================================================================

  # Feed
  def feed
    @group = UserGroup.find_by(user_id: id, name: "friends")
    @group_members = @user.relationships.where(user_id: id, 
                                               group_id: @group.id)
    ids ||= []
    @group_members.each { ids << |x|.id }
    ids << id
    Picture.where("album_id = ?", Album.where("user_id = ?", User.find_all_by_id(ids)).id)
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago 
  end 

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token  
    update_attribute(:remember_digest, User.digest(remember_token))
  end 

  # returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget 
    update_attribute(:remember_digest, nil)
  end 

  def downcase_email
    self.email = email.downcase 
  end

  def activate 
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
    UserGroup.insert_new(self, "Friends")
    UserGroup.insert_new(self, "Family")
    UserGroup.insert_new(self, "Blocked Users")
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now 
  end

  def create_activation_digest
    self.activation_token = User.new_token 
    self.activation_digest = User.digest(activation_token)
  end 

  def create_reset_digest 
    self.reset_token = User.new_token 
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end 

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now 
  end 
  # =========================================================================

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:find, :edit, :update, :destroy, :settings]
  before_action :correct_user, only: [:edit, :update, :settings]
  before_action :admin_user, only: :destroy 
  before_action :blocked_user, only: :show 

  def new
    @user = User.new 
  end 

  def show
    if !params[:id] && !logged_in?
      flash[:danger] = "Please log in to see your profile."
      redirect_to login_path 
    elsif !@user
      @user = current_user 
    end 

    # @user = User.find(params[:id])
    @relationships = @user.relationships + @user.inverse_relationships
    @albums = @user.albums.paginate(page: params[:page])

    redirect_to login_path and return unless @user.activated? 
  end

  def home
    if !params[:id] && !logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path 
    elsif !@user
      @user = current_user 
    end 

    @feed_items = @user.feed.paginate(page: params[:page])
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update 
    if @user.update_attribute(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user 
    else 
      render 'edit'
    end 
  end 

  def index  
    @users = User.where(activated: true).paginate(page: params[:page])
  end 

  def create
    @user = User.new(user_params)

    if @user.save 
      # log_in @user 
      # flash[:success] = "You have successfully created your account!"
      # redirect_to @user 
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account"
      redirect_to login_path
    else 
      render "new"
    end
  end 

  def settings 

  end 

  def destroy
    User.find(params[:id]).destroy 
    flash[:success] = "User deleted"
    redirect_to users_url 
  end 

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :username, :email, :password, :password_confirmation)
  end 

  # Redirects a user if they are on the Blocked Users
  # list of the person who's profile they're viewing
  def blocked_user
    is_blocked = false 

    if params[:id]
      @user = User.find(params[:id])

      for r in current_user.inverse_relationships
        if r.usergroup.name == "Blocked Users" && r.user.id == @user.id 
          is_blocked = true 
          break 
        end 
      end 
    end

    if is_blocked
      flash[:info] = "This user has chosen to keep their profile hidden."
      redirect_to login_path 
    end 
  end 

  def correct_user
    if params[:id]
      @user = User.find(params[:id])
    else 
      @user = current_user 
    end 
    redirect_to(login_path) unless current_user?(@user)
  end 

  def admin_user
    redirect_to(login_path) unless current_user.admin? 
  end 

end

app/helpers/users_helper.rb
module UsersHelper
  def get_user(id)
    return User.find_by(id: id)
  end
end

app/views/users/edit.html.erb
<% provide(:title, "FotoShare - Edit Profile") %>
<% provide(:maintitle, "Edit Profile") %>

<%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>
  
  <div class="form-group">
    <%= f.label :firstname %> <br />
    <%= f.text_field :firstname, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :lastname %> <br />
    <%= f.text_field :lastname, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :username %> <br />
    <%= f.text_field :username, :disabled => "disabled", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %> <br />
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %> <br />
    <%= f.password_field :password, :class => "form-group" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %> <br />
    <%= f.password_field :password_confirmation, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Edit Profile", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/find.html.erb
<table border="0">
	<% @users.each do |user| %>
		<% if user.id != current_user.id %>
			<tr>
				<td>
					<strong><%= user.username %></strong>
				</td>
				<td>
					<span class="greyed italic">(<%= user.firstname + user.lastname %>)</span>
				</td>
				<td>
					<%= link_to "Add Friend", relationships_path(:other_user_id => user, :relationship_type => "friend"), :method => :post %>
				</td>
			</tr>
		<% end %>
	<% end %>
</table>

app/views/users/home.html.erb
<% provide(:maintitle, "#{current_user.name}'s Home") %>
<% provide(:title, "#{current_user.name}'s Home") %>
<% if @feed_items.any? %>
  <ol class="feed_items">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/users/index.html.erb
<% provide(:maintitle, "Find Users") %>

<%= will_paginate %> 

<table border="0">
  <% @users.each do |user| %>
    <% if user.id != current_user.id %>
      <tr>
	<td>
	  <strong><%= link_to user.username, user %></strong>
	</td>
	<td>
	  <span class="greyed italic">(<%= user.firstname + " " + user.lastname %>)</span>
	</td>
	<td>
	  <ul>
	    <% current_user.user_groups.each do |group| %>
	      <li>
		<%= link_to "Add to \"#{group.name}\"", relationships_path(:other_user_id => user, :group_id => group), :method => :post %> 
	      </li>	
	    <% end %>
	  </ul>
	</td>
	<% if current_user.admin? && !current_user?(user) %>
	  <td>
	    <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
	  </td>
	<% end %>
      </tr>
    <% end %>
  <% end %>
</table>

<%= will_paginate %> 

app/views/users/new.html.erb
<% provide(:title, "FotoShare - Sign up") %>
<% provide(:maintitle, "Sign up") %>

<%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>

  <div class="form-group">
    <%= f.label :firstname, "First Name" %> <br />
    <%= f.text_field :firstname, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :lastname, "Last Name" %> <br />
    <%= f.text_field :lastname, :class => "form-control" %> 
  </div>

  <div class="form-group">
    <%= f.label :username %> <br />
    <%= f.text_field :username, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %> <br />
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %> <br />
    <%= f.password_field :password, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Confirm Password" %> <br />
    <%= f.password_field :password_confirmation, :class => "form-control" %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/users/show.html.erb
<% if @user.id == current_user.id %>
  <% provide(:maintitle, "Hello #{@user.username}!") %>
<% else %>
  <% provide(:maintitle, "#{@user.name}'s Profile") %>
<% end %>

<h3>Albums</h3>
<ul class="albums"">
  <% if @user.albums.any? %>
      <%= render @albums %>
    <%= will_paginate @albums %>
  <% end %>
</ul>

<h3>Groups</h3>
<ul>
  <% @user.user_groups.each do |group| %>
    <li>
      <%= group.name %>
    </li>
  <% end %>
</ul>

<h3>Relationships</h3>
<ul>
  <% @relationships.each do |r| %>
    <li>
      <% if r.relationship.username != current_user.username %>
	<%= r.relationship.username %>
      <% else %>
	<%= r.user.username %>
      <% end %>
      Group: <%= r.usergroup.name %> 
    </li>
  <% end %>
</ul>	

<% if @user.id == current_user.id %>
  <h3>Pending Relationship Requests to you</h3>
  <ul>
    <% for r in @user.inverse_pending_relationships %>
      <li>
	<%= r.relationship.username %>
	Group: <%= r.usergroup.name %> 
	<%= link_to "accept", relationship_path(r, :status => "accept"), :method => :put %>
	<%= link_to "ignore", relationship_path(r, :status => "ignore"), :method => :put %>
      </li>
    <% end %>
  </ul>

  <h3>Pending Relationship Requests from you</h3>
  <ul>
    <% for r in @user.pending_relationships %>
      <li>
	<%= r.relationship.username %>
	Group: <%= r.usergroup.name %> 
	<%= link_to "remove", r, :method => :delete %> 
      </li>
    <% end %>
  </ul>
<% end %>