config/routes.rb
Rails.application.routes.draw do
  get 'user_groups/index'

  get 'user_groups/new'

  get 'user_groups/create'

  get 'user_groups/edit'

  get 'user_groups/update'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'home#index'

  resources :users

  get 'sessions/new'
  get 'sessions/destroy'

  get 'signup' => 'users#new'
  get 'find'   => 'users#index'
  get 'profile' => 'users#show'
  get 'home' => 'users#home'
  get 'profile/edit' => 'users#edit'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :relationships
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :user_groups

  resources :albums
  resources :pictures, only: [:new, :create, :edit, :update, :destroy]

end

app/views/shared/_album_error_messages.html.erb
<% if @album.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@album.errors.count, "error") %>.
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/shared/_group_error_messages.html.erb
<% if @group.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@group.errors.count, "error") %>.
            <ul>
                <% @group.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/shared/_header.html.erb
<div class="row demo-row">
  <div class="col-xs-12">
    <nav class="navbar navbar-inverse navbar-embossed topnav" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
          <span class="sr-only">Toggle navigation</span>
        </button>
        <% if logged_in? %>
          <a class="navbar-brand" href="<%= home_path %>">FotoShare</a>
        <% else %>
          <a class="navbar-brand" href="<%= root_path %>">FotoShare</a>
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse-01">
        <ul class="nav navbar-nav navbar-left">
          <% if !logged_in? %>
            <li>
              <%= link_to "Login", login_path %>
            </li>
            <li>
              <%= link_to "Sign up", signup_path %>
            </li>
          <% end %>
        </ul>
        <form class="navbar-form navbar-right" action="#" role="search">
          <div class="form-group">
            <div class="input-group">
              <input class="form-control" id="navbarInput-01" type="search" placeholder="Search">
	      <span class="input-group-btn">
		<button type="submit" class="btn"><span class="fui-search"></span></button>
	      </span>
            </div>
          </div>
        </form>
        <% if logged_in? %>
	  <ul class="nav navbar-nav navbar-right rightnav">
	    <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<span class="fui-alert-circle"></span> 
		<% if current_user.inverse_pending_relationships.length > 0 %>
		  <span class="navbar-unread">
		    <%= current_user.inverse_pending_relationships.length %>
		  </span>
		<% end %>
		<b class="caret"></b>
	      </a>
	      <span class="dropdown-arrow"></span>
	      <ul class="dropdown-menu">
		<% if current_user.inverse_pending_relationships.length == 0 %>
		  <li>
		    <a href="">(no relationship requests)</a>
		  </li>
		<% else %>
		  <% for r in current_user.inverse_pending_relationships %>
		    <li>
		      <a href="">
			<%= r.relationship.firstname + " " + r.relationship.lastname %>
			wants you add you to: <%= r.usergroup.name %>
		      </a>
		    </li>
		  <% end %>
		<% end %>
	      </ul>
	    </li>
	    <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
		<span class="fui-plus"></span>
		<b class="caret"></b>
	      </a>
	      <span class="dropdown-arrow"></span>
	      <ul class="dropdown-menu">
		<li><a href="<%= new_user_group_path %>">Create a group</a></li>
		<li class="divider"></li>
		<li><a href="<%= new_album_path %>">Create an album</a></li>
		<li><a href="<%= new_picture_path %>">Upload a photo</a></li>
	      </ul>
	    </li>
	    <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<span class="fui-user"></span> 
		<b class="caret"></b>
	      </a>
	      <span class="dropdown-arrow"></span>
	      <ul class="dropdown-menu">
                <li>
                  <%= link_to "Home", home_path %>
		<li>
		  <%= link_to "Profile", profile_path %>
		</li>
		<li>
		  <a href="">Settings</a>
		</li>
		<li class="divider"></li>
		<li>
		  <%= link_to "Log out", logout_path, method: "delete" %>
		</li>
	      </ul>
	    </li>
	  </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </nav><!-- /navbar -->
  </div>
</div> <!-- /row -->

app/views/shared/_picture_error_messages.html.erb
<% if @picture.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@picture.errors.count, "error") %>.
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>